package mikrotik

import (
	"encoding/json"
	"fmt"
	"net/netip"
	"os"
	"strings"
	"time"
)

func WriteScript(path, listName string, prefixes []netip.Prefix, generatedAt time.Time, reset bool) error {
	var b strings.Builder

	b.WriteString("# Generated by mikrotik-iran-address-list\n")
	b.WriteString(fmt.Sprintf("# Generated at %s\n", generatedAt.UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("# Address list: %s\n", listName))
	b.WriteString("\n")

	if reset {
		b.WriteString(fmt.Sprintf("/ip firewall address-list remove [find where list=\"%s\"]\n", listName))
		b.WriteString(fmt.Sprintf("/ipv6 firewall address-list remove [find where list=\"%s\"]\n", listName))
		b.WriteString("\n")
	}

	var (
		hasV4 bool
		hasV6 bool
	)

	for _, prefix := range prefixes {
		if prefix.Addr().Is4() {
			if !hasV4 {
				b.WriteString("/ip firewall address-list\n")
				hasV4 = true
			}
			b.WriteString(fmt.Sprintf("add list=\"%s\" address=%s\n", listName, prefix))
		}
	}

	if hasV4 {
		b.WriteString("\n")
	}

	for _, prefix := range prefixes {
		if prefix.Addr().Is6() {
			if !hasV6 {
				b.WriteString("/ipv6 firewall address-list\n")
				hasV6 = true
			}
			b.WriteString(fmt.Sprintf("add list=\"%s\" address=%s\n", listName, prefix))
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func WritePlainList(path string, prefixes []netip.Prefix) error {
	lines := make([]string, 0, len(prefixes))
	for _, prefix := range prefixes {
		lines = append(lines, prefix.String())
	}

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644)
}

type Report struct {
	GeneratedAt  time.Time      `json:"generated_at"`
	ListName     string         `json:"list_name"`
	SourceCount  int            `json:"source_count"`
	PrefixCount  int            `json:"prefix_count"`
	IPv4Count    int            `json:"ipv4_count"`
	IPv6Count    int            `json:"ipv6_count"`
	Sources      []SourceReport `json:"sources"`
	FailedSource []string       `json:"failed_sources,omitempty"`
}

type SourceReport struct {
	Name        string `json:"name"`
	URL         string `json:"url"`
	PrefixCount int    `json:"prefix_count"`
}

func (r Report) WriteJSON(path string) error {
	payload, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	payload = append(payload, '\n')
	return os.WriteFile(path, payload, 0o644)
}
